[project]
name = "05-secure-data-encryption"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=44.0.2",
    "pyarrow==16.0.0",
    "streamlit==1.37.1",
]
